### PR TITLE
Removed check for erlang versions

### PR DESCRIPTION
**Pull request by Taure**
Since we dropped Erlang < 23 we can drop all checks for logger etc.

### CODE REVIEW

**Comment by burbas** [comment]
Sorry for hijacking this branch, but thought we could remove the `nova_logger.hrl`-file and all modules that made use of that.

**Comment by Taure** [comment]
That is fine but still some issue with build.

**Comment by burbas** [comment]
Think it's fine to merge this now when it passes build-step

**Review by burbas — COMMENTED** [review]
Looks good 👍

**Pull request merged**
