### PR TITLE
feat: Models in Nova

### PR DESCRIPTION
**Pull request by burbas**
Introducing models in Nova using a modified boss_db. Our hope is that we can merge our fork of boss_db into the main line.

Our fork of boss_db can be found here:
https://github.com/burbas/boss_db

### CODE REVIEW

**Comment by Taure** [comment]
Could we change this to a draft PR until it is done?

**Comment by Taure** [comment]
Before we should merge this to master. We should tag and release our boss_db to hex.

**Review by Taure — CHANGES_REQUESTED** [review]
Just a block until we have tested this branch.

**Comment by burbas** [comment]
> Just a block until we have tested this branch.

I've tested it with my setup and it works - but would be great if you also could try it out to see if it's working as expected on your end. I'll send a message to boss_db-repo and ask if we can put out our version.

**Comment by burbas** [comment]
@Taure Have you managed to test this yet?

**Comment by burbas** [comment]
Closing this since it's way outdated.

**Pull request closed without merging**
