### PR TITLE
Make JSON-lib Nova uses configurable. 

### LINKED ISSUE #160: Change json lib
I ran a benchmark with https://github.com/lpil/thoas, and it was a huge difference. Also, Thoas is all Erlang without any other dependencies, and it looks nice. Maybe it could be worth adding Thoas and using that for the `{json, ... }` part?

encode:

```
With input Pokedex
Name ips average deviation median 99th %
thoas 441.98 2.26 ms ±73.13% 1.05 ms 6.23 ms
jhn_stdlib - json 268.83 3.72 ms ±42.94% 4.43 ms 6.97 ms

Comparison:
thoas 441.98
jhn_stdlib - json 268.83 - 1.64x slower +1.46 ms

Memory usage statistics:

Name Memory usage
thoas 0.79 MB
jhn_stdlib - json 1.74 MB - 2.20x memory usage +0.95 MB

```
decode:

```
With input Pokedex
Name ips average deviation median 99th %
thoas 1.21 K 0.82 ms ±14.09% 0.81 ms 1.18 ms
jhn_stdlib - json 0.0996 K 10.04 ms ±4.76% 9.95 ms 11.88 ms

Comparison:
thoas 1.21 K
jhn_stdlib - json 0.0996 K - 12.17x slower +9.21 ms

Memory usage statistics:

Name Memory usage
thoas 0.38 MB
jhn_stdlib - json 8.03 MB - 21.08x memory usage +7.65 MB
```

### PR DESCRIPTION
**Pull request by burbas**
This is done with setting `json_lib` in your application configuration. Is the config is missing it will default to `thaos`.

The module defined with `json_lib` should have two functions exported:
`encode/1 -> binary() | iolist().`
`decode/1 -> {ok, map()}`

Closes #160

### CODE REVIEW

**Comment by burbas** [comment]
@Taure Any comments around this?

**Comment by Taure** [comment]
I haven't tested this because PR #161 failed. :) But I can have a look tomorrow.

**Comment by Taure** [comment]
I think it looks good. But I think it is time for us to add a config guide that we update with how you can configure everything in Nova.

**Review by Taure — CHANGES_REQUESTED** [review]
I would like a short guide of how you configure this in sys.config.

**Pull request merged**
