### PR TITLE
Pass controller_data into security_plugin auth function

### PR DESCRIPTION
**Pull request by fancycade**
Return existing controller data + auth_data

Unfortunately this is a breaking change with the req key, but I would like to argue that it is the correct way.

1. This change makes writing auth functions exactly like a controller. Making it easier to copy existing controller code.
2. This change is needed if using request_plugin and the security_plugin.

It could be possible to feature flag this with a config variable to make it backwards compatible.

### CODE REVIEW

**Comment by Taure** [comment]
Thank you for the PR. May I ask in what cases it doesn't work to use the security plugin and request plugin?

I have used them both in many applications but might some case that we haven't thought of.

https://github.com/widgrensit/chatli this is a chat server that uses Nova with auth and uses both the security plugin and request plugin.

**Review by burbas — COMMENTED** [review]
Really like this change. This enables the user to actually create an initial controller_data-object in the pre-plugins.

**Comment by Taure** [comment]
Yeah, I like it also. But was wondering what we try to solve here that we couldn't do with the old solution.

0.8 will break things anyway so this could be good to merge into that release.

**Comment by fancycade** [comment]
@Taure In my case I was using request_plugin first and using the ControllerData fields in my auth function.

Technically speaking, you are right. I can solve this in a different way (likely better).

Subjectively speaking, I still think it would be better if the security_plugin behavior was more similar to controllers. Thus being a bit more intuitive to use.

**Comment by Taure** [comment]
@fancycade I was more curious because I and @burbas have built this so for us things are "easy".  I appreciate what you shared so we can discuss it and change things to be more intuitive. Like mentioned before having an initial controller_data object in pre-plugins is a good idea.  It will unify things in a good way.

And we are doing big changes in the upcoming 0.8 release that will change things so we can add this also.

**Comment by fancycade** [comment]
> @fancycade I was more curious because I and @burbas have built this so for us things are "easy". I appreciate what you shared so we can discuss it and change things to be more intuitive. Like mentioned before having an initial controller_data object in pre-plugins is a good idea. It will unify things in a good way.

Great I am glad this can be included!

 I have made my first nova app [here](https://git.sr.ht/~fancycade/feedme). So you can get a bit more context where I am coming from. My hope was to make helpful patches while being a first time user was fresh on my mind.

**Comment by burbas** [comment]
> @Taure In my case I was using request_plugin first and using the ControllerData fields in my auth function.
> 
> Technically speaking, you are mostly right. I can solve this in a different way (likely better). However, I do think the security_plugin was overwriting the ControllerData coming from request_plugin and I couldn't see that data in my controller.
> 
> Subjectively speaking, I still think it would be better if the security_plugin behavior was more similar to controllers. Thus being a bit more intuitive to use.

You are correct - the security controller were actually overwriting the controller-data. I think your change makes a lot of sense. I don't think there's a problem with breaking changes at this stage since version 0.8 will break a lot of things :-).

And thanks for your contribution - always fun to see people using Nova.

**Pull request merged**
