### PR TITLE
move templates to rebar3_nova plugin

### PR DESCRIPTION
**Pull request by longlene**
can setup nova development env quickly, no curl or wget needed
please also review: https://github.com/novaframework/rebar3_nova/pull/1

### CODE REVIEW

**Comment by burbas** [comment]
Thank you! It's a good idea to move it, but with this you loose the ability to create a new app in an easy way eg `rebar3 new nova my_nova_app`. That's why we have the installation-script :-). If you can solve that I don't see any reason going forward with this MR.

**Review by burbas — CHANGES_REQUESTED** [review]
We really need the curl/wget-command in order to install templates to rebar3 (Enables us to create new apps with nova `rebar3 new nova my_app`.

**Comment by longlene** [comment]
@burbas rebar3 can auto detect the templates in rebar3 plugin priv directory.
Just try the following steps:
1. backup the template directory installed by the install.sh and remove these template files
2. add plugin config to rebar3 global config file: ~/.config/rebar3/rebar.config
3. run `rebar3 new nova hello`, so rebar3 will fetch rebar3_nova from github(maybe future in hex.pm?) and create the project from template

**Comment by longlene** [comment]
@burbas I've added my repo to my `~/.config/rebar3/rebar.config`
```erlang
{plugins, [
           {rebar3_nova, {git, "https://github.com/longlene/rebar3_nova.git"}}
          ]}.
```

rebar3 fetched templates to `~/.cache/rebar3/plugins/rebar3_nova/priv/templates` automatically and find these files

**Comment by buurbas** [comment]
Okay, now I'm up to speed :). Think it's a solid solution. My only concern is that we loose the one-line install script.

What do you think of, in addition to your changes also provide a escript that you could run via wget/curl to inject the plugin-row into rebar.config? I can write it, but want your input on it aswell.

**Comment by Taure** [comment]
Could we have both for a while?

one-line install script can still live and we can add this as an option if
you also want to use the rebar3 nova plugin. When this plugin is mature
enough we could remove the script?

Den fre 15 jan. 2021 kl 15:15 skrev buurbas <notifications@github.com>:

**Comment by longlene** [comment]
Sounds good, so can we close the pr?

**Pull request closed without merging**
